# Generated by Django 2.2.2 on 2019-08-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190827_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
